version: "3.9"
services:
  
 nour:
  image: mongo
  ports:
   - "27017:27017"
  volumes:
    - ./data:/data/db
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: nour
    MONGO_INITDB_ROOT_PASSWORD: nour
 
 nour-express:
  image: mongo-express
  ports:
   - "8081:8081"
  restart: always
  depends_on:
   - nour
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: nour
    ME_CONFIG_MONGODB_ADMINPASSWORD: nour
    ME_CONFIG_MONGODB_SERVER: nour
volumes:
data: {}